"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import raven, dj_database_url, os, logging
from unipath import Path
from decouple import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=os.environ.get('SECRET_KEY'), cast=str)
FILESTACK_KEY = config('FILESTACK_KEY', default=os.environ.get('FILESTACK_KEY'), cast=str)

AUTH_USER_MODEL = 'core.user'
LOGIN_URL = '/login/'
LOGOUT_URL = '/logout/'
LOGIN_REDIRECT_URL = '/'

PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.MD5PasswordHasher',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #config('DEBUG', default=os.environ.get('DEBUG'), cast=bool)
TEMPLATE_DEBUG = DEBUG

DEBUG_TOOLBAR_CONFIG = {'INTERCEPT_REDIRECTS': False,}

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=os.environ.get('ALLOWED_HOSTS'), cast=tuple)
INTERNAL_IPS  = config('DEBUG_HOSTS', default=os.environ.get('DEBUG_HOSTS'), cast=tuple)

# Email settings

EMAIL_HOST = config('EMAIL_HOST', default=os.environ.get('EMAIL_HOST'), cast=str)
EMAIL_PORT = config('EMAIL_PORT', default=os.environ.get('EMAIL_PORT'), cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default=os.environ.get('EMAIL_HOST_USER'), cast=str)
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default=os.environ.get('EMAIL_HOST_PASSWORD'), cast=str)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=os.environ.get('EMAIL_USE_TLS'), cast=bool)
DEFAULT_FROM_EMAIL = 'StudentMy Team <admin@studentmy.com>'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # During development only

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL  = '/static/'
STATIC_ROOT = BASE_DIR.child('static')

# Application definition
INSTALLED_APPS = [
    'django.contrib.auth',
    'core',
    'tests',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 

    # Extra Apps:
    
    'corsheaders',
    'widget_tweaks',
    'debug_toolbar',
    'raven.contrib.django.raven_compat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #Extra Middlewares:
    
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                #Extra context processors:

                #'django.core.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
DATABASES = {
    'default': dj_database_url.parse('sqlite:///' + BASE_DIR.child(config('SQLITE_NAME', default=os.environ.get('SQLITE_NAME'), cast=str))),
    #'default': dj_database_url.parse(config('DATABASE_URL', default=os.environ.get('DATABASE_URL'), cast=str), conn_max_age=600),
    'extra': dj_database_url.parse('sqlite:///' + BASE_DIR.child(config('SQLITE_NAME', default=os.environ.get('SQLITE_NAME'), cast=str)))
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
#

from django.utils.translation import ugettext_lazy as gettext

LANGUAGES = (
    ('es', gettext('Spanish')),
    ('en', gettext('English')),
    ('pt-br', gettext('Brazilian Portuguese')),
    ('ja', gettext('Japanese'))
)

TIME_ZONE = 'America/Fortaleza'
USE_I18N = True
USE_L10N = True
USE_TZ = True

DEFAULT_CHARSET = 'utf-8'

LOCALE_PATHS = (
    BASE_DIR.child('locale'),
)
#
MEDIA_URL   = '/media/'
MEDIA_ROOT  = BASE_DIR.child('media')

STATICFILES_DIRS = (
    BASE_DIR.child('custom'),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'npm.finders.NpmFinder'
)

# Cors Settings:

CORS_ORIGIN_WHITELIST = config('CORS_ORIGIN_WHITELIST', default=os.environ.get('CORS_ORIGIN_WHITELIST'), cast=str)
CORS_ALLOW_METHODS    = config('CORS_ALLOW_METHODS', default=os.environ.get('CORS_ALLOW_METHODS'), cast=str)

# Raven Settings:

RAVEN_CONFIG = {
    'dsn': config('RAVEN_DSN', default=os.environ.get('RAVEN_DSN'), cast=str),
    # If you are using git, you can also automatically configure the release based on the git info.
    #'release': raven.fetch_git_sha(BASE_DIR.child('.git').child('HEAD')),
}

NPM_ROOT_PATH = BASE_DIR.parent

# django-debug-toolbar

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]