# Generated by Django 2.0.3 on 2018-03-22 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180321_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('PPR', 'Per Price'), ('PPE', 'Per Percentage')], default='PPR', max_length=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expiration_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='group',
        ),
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.Course'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_coupons', to='core.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='contents',
            field=models.ManyToManyField(to='core.Content'),
        ),
        migrations.AddField(
            model_name='student',
            name='contents',
            field=models.ManyToManyField(to='core.Content'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contents',
            field=models.ManyToManyField(to='core.Content'),
        ),
    ]
