# Generated by Django 2.0.3 on 2018-03-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180321_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='who_is',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher')], default='TE', max_length=2),
        ),
    ]
