# Generated by Django 2.0.3 on 2018-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumb',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='thumb',
            field=models.CharField(max_length=255),
        ),
    ]
