# Generated by Django 2.0.3 on 2018-08-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='student',
            new_name='user',
        ),
    ]
