# Generated by Django 2.0.6 on 2018-06-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dish',
        ),
        migrations.AddField(
            model_name='order',
            name='dish_order',
            field=models.ManyToManyField(related_name='orders', to='core.Dish'),
        ),
    ]
