# Generated by Django 2.0.6 on 2018-06-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180623_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='adress',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='dsfsd', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
