# Generated by Django 2.0.6 on 2018-07-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180623_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishrating',
            old_name='customer',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='profile',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='restaurantrating',
            old_name='customer',
            new_name='owner',
        ),
    ]
